### ISSUE TITLE
ambiguous import: found package in multiple modules

### ISSUE THREAD

**Issue by frankpacini** [galeone/tfgo#56] opened 2021-07-16 14:41 UTC
I am importing the packages as suggested in the examples:
```
tf "github.com/galeone/tensorflow/tensorflow/go"
tg "github.com/galeone/tfgo"
```
and get the following error

```
main.go:11:2: ambiguous import: found package github.com/galeone/tensorflow/tensorflow/go in multiple modules:
        github.com/galeone/tensorflow v2.3.1+incompatible (~/.gvm/pkgsets/go1.15.8/global/pkg/mod/github.com/galeone/tensorflow@v2.3.1+incompatible/tensorflow/go)
        github.com/galeone/tensorflow/tensorflow/go v0.0.0-20210519172502-4018d721b591 (~/.gvm/pkgsets/go1.15.8/global/pkg/mod/github.com/galeone/tensorflow/tensorflow/go@v0.0.0-20210519172502-4018d721b591)

../../.gvm/pkgsets/go1.15.8/global/pkg/mod/github.com/galeone/tfgo@v0.0.0-20210519185601-7d7131a16882/ops.go:24:2: ambiguous import: found package github.com/galeone/tensorflow/tensorflow/go/op in multiple modules:
        github.com/galeone/tensorflow v2.3.1+incompatible (~/.gvm/pkgsets/go1.15.8/global/pkg/mod/github.com/galeone/tensorflow@v2.3.1+incompatible/tensorflow/go/op)
        github.com/galeone/tensorflow/tensorflow/go v0.0.0-20210519172502-4018d721b591 (~/.gvm/pkgsets/go1.15.8/global/pkg/mod/github.com/galeone/tensorflow/tensorflow/go@v0.0.0-20210519172502-4018d721b591/op)

```

After running go build the relevant section of my go.sum looks like:
```
github.com/galeone/tensorflow v1.15.4 h1:TQeJss9Aeipg2K6kNwfqKRNpDLLwBdCouRKdCfzQ2pg=
github.com/galeone/tensorflow v2.3.1+incompatible h1:RRiPEbcVK2IghF7YFDDF33tx+XMr2NuCriDBlMWYm5s=
github.com/galeone/tensorflow v2.3.1+incompatible/go.mod h1:tPYvIhe58Qvzh/hJfdy0881FcAnouYskaz5tNIDEeMA=
github.com/galeone/tensorflow/tensorflow/go v0.0.0-20210519172502-4018d721b591 h1:1UOml7GsssubL3OW53W9+kBk5BQICiG95TNXAmTrrsM=
github.com/galeone/tensorflow/tensorflow/go v0.0.0-20210519172502-4018d721b591/go.mod h1:0LCzFWUL71lYeHtxlL/15k/+5ZKVzJk6Z+hLX1UBoUQ=
github.com/galeone/tfgo v0.0.0-20210519185601-7d7131a16882 h1:YrghpSKeSJYE24fn/NzuAVXukc9npefUV6j10sgnj8Y=
github.com/galeone/tfgo v0.0.0-20210519185601-7d7131a16882/go.mod h1:05ASagqJQa1Xev+FhblKviD9OAbRUWN4XAN2A1+aTd0=
```

and under github.com/galeone the following packages are installed:
```
tensorflow          
tensorflow@v2.3.1+incompatible
tensorflow@v1.15.4  
tfgo@v0.0.0-20210519185601-7d7131a16882
```

**Comment by galeone** [comment] 2021-07-16 15:00
Hm.. that's really strange. I just tried in a clean environment and it works like it should:


```sh
mkdir $GOPATH/src/github.com/galeone/test
go mod init
go get github.com/galeone/tfgo
curl https://raw.githubusercontent.com/galeone/tfgo/master/README.md |grep "package main" -A 23 -m 1 > main.go
go run main.go
```

Produces

```
2021-07-16 16:58:00.440395: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-07-16 16:58:00.479746: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-07-16 16:58:00.481494: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2021-07-16 16:58:00.714140: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:17:00.0 name: NVIDIA GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.6575GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s
2021-07-16 16:58:00.714565: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 1 with properties: 
pciBusID: 0000:65:00.0 name: NVIDIA GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.6575GHz coreCount: 28 deviceMemorySize: 10.91GiB deviceMemoryBandwidth: 451.17GiB/s
2021-07-16 16:58:00.714589: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-07-16 16:58:00.716412: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-07-16 16:58:00.716453: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
2021-07-16 16:58:00.717085: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcufft.so.10
2021-07-16 16:58:00.717291: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2021-07-16 16:58:00.717784: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusolver.so.11
2021-07-16 16:58:00.718223: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusparse.so.11
2021-07-16 16:58:00.718318: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2021-07-16 16:58:00.726767: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0, 1
2021-07-16 16:58:00.726793: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-07-16 16:58:01.258206: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-07-16 16:58:01.258237: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 1 
2021-07-16 16:58:01.258243: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N Y 
2021-07-16 16:58:01.258248: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 1:   Y N 
2021-07-16 16:58:01.260209: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10430 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce GTX 1080 Ti, pci bus id: 0000:17:00.0, compute capability: 6.1)
2021-07-16 16:58:01.260927: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10260 MB memory) -> physical GPU (device: 1, name: NVIDIA GeForce GTX 1080 Ti, pci bus id: 0000:65:00.0, compute capability: 6.1)
2021-07-16 16:58:01.261173: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
2021-07-16 16:58:01.261866: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 3600000000 Hz
Y:  [[200] [-200]] Z:  [[200] [-200]]
Y == A true
Z == A false
```

as expected.

Are you running the very same steps? Be sure your go environment has no TensorFlow package installed globally, or tfgo installed to some old version (before the advent of go.mod).

Just for completeness, the content of the go.mod and go.sum are the following:

```
module github.com/galeone/test

go 1.16

require github.com/galeone/tfgo v0.0.0-20210519185601-7d7131a16882 // indirect
```

and this is the go.sum
````
cloud.google.com/go v0.26.0/go.mod h1:aQUYkXzVsufM+DwF1aE+0xfcU+56JwCaLick0ClmMTw=
github.com/BurntSushi/toml v0.3.1/go.mod h1:xHWCNGjB5oqiDr8zfno3MHue2Ht5sIBksp03qcyfWMU=
github.com/census-instrumentation/opencensus-proto v0.2.1/go.mod h1:f6KPmirojxKA12rnyqOA5BBL4O983OfeGPqjHWSTneU=
github.com/client9/misspell v0.3.4/go.mod h1:qj6jICC3Q7zFZvVWo7KLAzC3yx5G7kyvSDkc90ppPyw=
github.com/envoyproxy/go-control-plane v0.9.1-0.20191026205805-5f8ba28d4473/go.mod h1:YTl/9mNaCwkRvm6d1a2C3ymFceY/DCBVvsKhRF0iEA4=
github.com/envoyproxy/protoc-gen-validate v0.1.0/go.mod h1:iSmxcyjqTsJpI2R4NaDN7+kN2VEUnK/pcBlmesArF7c=
github.com/galeone/tensorflow/tensorflow/go v0.0.0-20210519172502-4018d721b591 h1:1UOml7GsssubL3OW53W9+kBk5BQICiG95TNXAmTrrsM=
github.com/galeone/tensorflow/tensorflow/go v0.0.0-20210519172502-4018d721b591/go.mod h1:0LCzFWUL71lYeHtxlL/15k/+5ZKVzJk6Z+hLX1UBoUQ=
github.com/galeone/tfgo v0.0.0-20210519185601-7d7131a16882 h1:YrghpSKeSJYE24fn/NzuAVXukc9npefUV6j10sgnj8Y=
github.com/galeone/tfgo v0.0.0-20210519185601-7d7131a16882/go.mod h1:05ASagqJQa1Xev+FhblKviD9OAbRUWN4XAN2A1+aTd0=
github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b/go.mod h1:SBH7ygxi8pfUlaOkMMuAQtPIUF8ecWP5IEl/CR7VP2Q=
github.com/golang/mock v1.1.1/go.mod h1:oTYuIxOrZwtPieC+H1uAHpcLFnEyAGVDL/k47Jfbm0A=
github.com/golang/protobuf v1.2.0/go.mod h1:6lQm79b+lXiMfvg/cZm0SGofjICqVBUtrP5yJMmIC1U=
github.com/golang/protobuf v1.3.2/go.mod h1:6lQm79b+lXiMfvg/cZm0SGofjICqVBUtrP5yJMmIC1U=
github.com/golang/protobuf v1.4.0-rc.1/go.mod h1:ceaxUfeHdC40wWswd/P6IGgMaK3YpKi5j83Wpe3EHw8=
github.com/golang/protobuf v1.4.0-rc.1.0.20200221234624-67d41d38c208/go.mod h1:xKAWHe0F5eneWXFV3EuXVDTCmh+JuBKY0li0aMyXATA=
github.com/golang/protobuf v1.4.0-rc.2/go.mod h1:LlEzMj4AhA7rCAGe4KMBDvJI+AwstrUpVNzEA03Pprs=
github.com/golang/protobuf v1.4.0-rc.4.0.20200313231945-b860323f09d0/go.mod h1:WU3c8KckQ9AFe+yFwt9sWVRKCVIyN9cPHBJSNnbL67w=
github.com/golang/protobuf v1.4.0/go.mod h1:jodUvKwWbYaEsadDk5Fwe5c77LiNKVO9IDvqG2KuDX0=
github.com/golang/protobuf v1.4.1/go.mod h1:U8fpvMrcmy5pZrNK1lt4xCsGvpyWQ/VVv6QDs8UjoX8=
github.com/golang/protobuf v1.5.0/go.mod h1:FsONVRAS9T7sI+LIUmWTfcYkHO4aIWwzhcaSAoJOfIk=
github.com/golang/protobuf v1.5.2 h1:ROPKBNFfQgOUMifHyP+KYbvpjbdoFNs+aK7DXlji0Tw=
github.com/golang/protobuf v1.5.2/go.mod h1:XVQd3VNwM+JqD3oG2Ue2ip4fOMUkwXdXDdiuN0vRsmY=
github.com/google/go-cmp v0.2.0/go.mod h1:oXzfMopK8JAjlY9xF4vHSVASa0yLyX7SntLO5aqRK0M=
github.com/google/go-cmp v0.3.0/go.mod h1:8QqcDgzrUqlUb/G2PQTWiueGozuR1884gddMywk6iLU=
github.com/google/go-cmp v0.3.1/go.mod h1:8QqcDgzrUqlUb/G2PQTWiueGozuR1884gddMywk6iLU=
github.com/google/go-cmp v0.4.0/go.mod h1:v8dTdLbMG2kIc/vJvl+f65V22dbkXbowE6jgT/gNBxE=
github.com/google/go-cmp v0.5.5/go.mod h1:v8dTdLbMG2kIc/vJvl+f65V22dbkXbowE6jgT/gNBxE=
github.com/prometheus/client_model v0.0.0-20190812154241-14fe0d1b01d4/go.mod h1:xMI15A0UPsDsEKsMN9yxemIoYk6Tm2C1GtYGdfGttqA=
golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2/go.mod h1:djNgcEr1/C05ACkg1iLfiJU5Ep61QUkGW8qpdssI0+w=
golang.org/x/exp v0.0.0-20190121172915-509febef88a4/go.mod h1:CJ0aWSM057203Lf6IL+f9T1iT9GByDxfZKAQTCR3kQA=
golang.org/x/lint v0.0.0-20181026193005-c67002cb31c3/go.mod h1:UVdnD1Gm6xHRNCYTkRU2/jEulfH38KcIWyp/GAMgvoE=
golang.org/x/lint v0.0.0-20190227174305-5b3e6a55c961/go.mod h1:wehouNa3lNwaWXcvxsM5YxQ5yQlVC4a0KAMCusXpPoU=
golang.org/x/lint v0.0.0-20190313153728-d0100b6bd8b3/go.mod h1:6SW0HCj/g11FgYtHlgUYUwCkIfeOF89ocIRzGO/8vkc=
golang.org/x/net v0.0.0-20180724234803-3673e40ba225/go.mod h1:mL1N/T3taQHkDXs73rZJwtUhF3w3ftmwwsq0BUmARs4=
golang.org/x/net v0.0.0-20180826012351-8a410e7b638d/go.mod h1:mL1N/T3taQHkDXs73rZJwtUhF3w3ftmwwsq0BUmARs4=
golang.org/x/net v0.0.0-20190213061140-3a22650c66bd/go.mod h1:mL1N/T3taQHkDXs73rZJwtUhF3w3ftmwwsq0BUmARs4=
golang.org/x/net v0.0.0-20190311183353-d8887717615a/go.mod h1:t9HGtf8HONx5eT2rtn7q6eTqICYqUVnKs3thJo3Qplg=
golang.org/x/oauth2 v0.0.0-20180821212333-d2e6202438be/go.mod h1:N/0e6XlmueqKjAGxoOufVs8QHGRruUQn6yWY3a++T0U=
golang.org/x/sync v0.0.0-20180314180146-1d60e4601c6f/go.mod h1:RxMgew5VJxzue5/jJTE5uejpjVlOe/izrB70Jof72aM=
golang.org/x/sync v0.0.0-20181108010431-42b317875d0f/go.mod h1:RxMgew5VJxzue5/jJTE5uejpjVlOe/izrB70Jof72aM=
golang.org/x/sync v0.0.0-20190423024810-112230192c58/go.mod h1:RxMgew5VJxzue5/jJTE5uejpjVlOe/izrB70Jof72aM=
golang.org/x/sys v0.0.0-20180830151530-49385e6e1522/go.mod h1:STP8DvDyc/dI5b8T5hshtkjS+E42TnysNCUPdjciGhY=
golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a/go.mod h1:STP8DvDyc/dI5b8T5hshtkjS+E42TnysNCUPdjciGhY=
golang.org/x/text v0.3.0/go.mod h1:NqM8EUOU14njkJ3fqMW+pc6Ldnwhi/IjpwHt7yyuwOQ=
golang.org/x/tools v0.0.0-20190114222345-bf090417da8b/go.mod h1:n7NCudcB/nEzxVGmLbDWY5pfWTLqBcC2KZ6jyYvM4mQ=
golang.org/x/tools v0.0.0-20190226205152-f727befe758c/go.mod h1:9Yl7xja0Znq3iFh3HoIrodX9oNMXvdceNzlUR8zjMvY=
golang.org/x/tools v0.0.0-20190311212946-11955173bddd/go.mod h1:LCzVGOaR6xXOjkQ3onu1FJEFr0SW1gC7cKk1uF8kGRs=
golang.org/x/tools v0.0.0-20190524140312-2c0ae7006135/go.mod h1:RgjU9mgBXZiqYHBnxXauZ1Gv1EHHAz9KjViQ78xBX0Q=
golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543/go.mod h1:I/5z698sn9Ka8TeJc9MKroUUfqBBauWjQqLJ2OPfmY0=
google.golang.org/appengine v1.1.0/go.mod h1:EbEs0AVv82hx2wNQdGPgUI5lhzA/G0D9YwlJXL52JkM=
google.golang.org/appengine v1.4.0/go.mod h1:xpcJRLb0r/rnEns0DIKYYv+WjYCduHsrkT7/EB5XEv4=
google.golang.org/genproto v0.0.0-20180817151627-c66870c02cf8/go.mod h1:JiN7NxoALGmiZfu7CAH4rXhgtRTLTxftemlI0sWmxmc=
google.golang.org/genproto v0.0.0-20190819201941-24fa4b261c55/go.mod h1:DMBHOl98Agz4BDEuKkezgsaosCRResVns1a3J2ZsMNc=
google.golang.org/genproto v0.0.0-20200526211855-cb27e3aa2013/go.mod h1:NbSheEEYHJ7i3ixzK3sjbqSGDJWnxyFXZblF3eUsNvo=
google.golang.org/grpc v1.19.0/go.mod h1:mqu4LbDTu4XGKhr4mRzUsmM4RtVoemTSY81AxZiDr8c=
google.golang.org/grpc v1.23.0/go.mod h1:Y5yQAOtifL1yxbo5wqy6BxZv8vAUGQwXBOALyacEbxg=
google.golang.org/grpc v1.27.0/go.mod h1:qbnxyOmOxrQa7FizSgH+ReBfzJrCY1pSN7KXBS8abTk=
google.golang.org/protobuf v0.0.0-20200109180630-ec00e32a8dfd/go.mod h1:DFci5gLYBciE7Vtevhsrf46CRTquxDuWsQurQQe4oz8=
google.golang.org/protobuf v0.0.0-20200221191635-4d8936d0db64/go.mod h1:kwYJMbMJ01Woi6D6+Kah6886xMZcty6N08ah7+eCXa0=
google.golang.org/protobuf v0.0.0-20200228230310-ab0ca4ff8a60/go.mod h1:cfTl7dwQJ+fmap5saPgwCLgHXTUD7jkjRqWcaiX5VyM=
google.golang.org/protobuf v1.20.1-0.20200309200217-e05f789c0967/go.mod h1:A+miEFZTKqfCUM6K7xSMQL9OKL/b6hQv+e19PK+JZNE=
google.golang.org/protobuf v1.21.0/go.mod h1:47Nbq4nVaFHyn7ilMalzfO3qCViNmqZ2kzikPIcrTAo=
google.golang.org/protobuf v1.22.0/go.mod h1:EGpADcykh3NcUnDUJcl1+ZksZNG86OlYog2l/sGQquU=
google.golang.org/protobuf v1.23.1-0.20200526195155-81db48ad09cc/go.mod h1:EGpADcykh3NcUnDUJcl1+ZksZNG86OlYog2l/sGQquU=
google.golang.org/protobuf v1.26.0-rc.1/go.mod h1:jlhhOSvTdKEhbULTjvd4ARK9grFBp09yW+WbY/TyQbw=
google.golang.org/protobuf v1.26.0 h1:bxAC2xTBsZGibn2RTntX0oH50xLsqy1OxA9tTL3p/lk=
google.golang.org/protobuf v1.26.0/go.mod h1:9q0QmTI4eRPtz6boOQmLYwt+qCgq0jsYwAQnmE0givc=
honnef.co/go/tools v0.0.0-20190102054323-c2f93a96b099/go.mod h1:rf3lG4BRIbNafJWhAfAdb/ePZxsR/4RtNHQocxwk9r4=
honnef.co/go/tools v0.0.0-20190523083050-ea95bdfd59fc/go.mod h1:rf3lG4BRIbNafJWhAfAdb/ePZxsR/4RtNHQocxwk9r4=
```

**Comment by frytoli** [comment] 2022-03-07 22:10
Hi there -- any updates on this? I'm trying to use tfgo in a Docker container with this Dockerfile:

```
FROM tensorflow/tensorflow:2.5.0

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
  apt-get install -y build-essential software-properties-common \
  libopencv-dev ffmpeg libavformat-dev git

# Grab go
COPY --from=golang:1.16 /usr/local/go/ /usr/local/go/

ENV PATH="/usr/local/go/bin:${PATH}"

# Set working directory
WORKDIR /gocr

# Copy over files
COPY ocr.go .
ADD models /gocr/models

# Init and build the app
RUN go mod init ocr && \
  go mod tidy && \
  go build

ENTRYPOINT ["/gocr/ocr"]
```

And my build breaks with the following error:
```
------                                                                                                                         
 > [stage-0 8/8] RUN go mod init ocr &&   go mod tidy &&   go build:                                                           
#13 0.322 go: creating new go.mod: module ocr                                                                                  
#13 0.324 go: to add module requirements and sums:                                                                             
#13 0.324       go mod tidy                                                                                                    
#13 0.391 go: finding module for package gocv.io/x/gocv                                                                        
#13 0.391 go: finding module for package github.com/galeone/tensorflow/tensorflow/go
#13 0.392 go: finding module for package github.com/galeone/tfgo
#13 0.667 go: downloading github.com/galeone/tensorflow v1.15.4
#13 1.005 go: downloading github.com/galeone/tfgo v0.0.0-20210914072119-caabdf830ee3
#13 1.128 go: downloading gocv.io/x/gocv v0.29.0
#13 19.60 go: downloading github.com/galeone/tensorflow v2.3.1+incompatible
#13 37.34 go: found github.com/galeone/tensorflow/tensorflow/go in github.com/galeone/tensorflow v2.3.1+incompatible
#13 37.34 go: found github.com/galeone/tfgo in github.com/galeone/tfgo v0.0.0-20210914072119-caabdf830ee3
#13 37.34 go: found gocv.io/x/gocv in gocv.io/x/gocv v0.29.0
#13 39.15 go: downloading github.com/galeone/tensorflow/tensorflow/go v0.0.0-20210519172502-4018d721b591
#13 39.83 ocr imports
#13 39.83 	github.com/galeone/tensorflow/tensorflow/go: ambiguous import: found package github.com/galeone/tensorflow/tensorflow/go in multiple modules:
#13 39.83 	github.com/galeone/tensorflow v2.3.1+incompatible (/root/go/pkg/mod/github.com/galeone/tensorflow@v2.3.1+incompatible/tensorflow/go)
#13 39.83 	github.com/galeone/tensorflow/tensorflow/go v0.0.0-20210519172502-4018d721b591 (/root/go/pkg/mod/github.com/galeone/tensorflow/tensorflow/go@v0.0.0-20210519172502-4018d721b591)
#13 39.83 ocr imports
#13 39.83 	github.com/galeone/tfgo imports
#13 39.83 	github.com/galeone/tensorflow/tensorflow/go/op: ambiguous import: found package github.com/galeone/tensorflow/tensorflow/go/op in multiple modules:
#13 39.83 	github.com/galeone/tensorflow v2.3.1+incompatible (/root/go/pkg/mod/github.com/galeone/tensorflow@v2.3.1+incompatible/tensorflow/go/op)
#13 39.83 	github.com/galeone/tensorflow/tensorflow/go v0.0.0-20210519172502-4018d721b591 (/root/go/pkg/mod/github.com/galeone/tensorflow/tensorflow/go@v0.0.0-20210519172502-4018d721b591/op)
------
executor failed running [/bin/sh -c go mod init ocr &&   go mod tidy &&   go build]: exit code: 1
```

My imports in `ocr.go` look like this:
```
import (
  "fmt"
  "image"
  "os"
  "path/filepath"

  tg "github.com/galeone/tfgo"
  tf "github.com/galeone/tensorflow/tensorflow/go"
  "gocv.io/x/gocv"
)
```

I'm pretty new to Go, so any advice would be greatly appreciated. Thank you for your help as well as for your work!

**Comment by frankpacini** [comment] 2022-03-07 22:55
I wasn't able to solve this issue. What I ended up doing was painstakingly fixing the defunc installation guide [here](https://github.com/tensorflow/build/tree/master/golang_install_guide), and then hosting the resulting package in a repository (no longer have access unfortunately). Hope this is able to get fixed either way. Best of luck!

**Comment by galeone** [comment] 2022-03-08 06:53
This is so strange. I wasn't (and still I'm not) able to reproduce this issue. What OS are you using?

**Comment by galeone** [comment] 2022-03-08 07:03
I just noticed that you were answering another user (Olivia) that now deleted her comment. Anyway, in that case, it was pretty clear why the error exists since she was using the tensorflow docker container and therefore still was the `tensorflow/go` package installed, and, thus my fork will conflict.

Anyway I'm going to close this issue because I cannot reproduce it locally even after months

**Closed by galeone** 2022-03-08 07:03 UTC
